### ISSUE TITLE
All mails sent twice

### ISSUE THREAD

**Issue by Albertus58** [XRPL-Labs/xumm-for-woocommerce#1]
After udating to V 0.3  New order received mail to webshop owner, Order received mail to customer and payment recived mail to customer all are sent twice.

**Comment by KoenPaas** [comment]
Thanks for creating an issue,
I think this is due to the fact that the plugin creates a note, it will automatically send another email, is that the case? Or is it in fact the **exact** same email twice?

**Comment by Albertus58** [comment]
It is exact the same mail(s)

**Comment by KoenPaas** [comment]
I'm unable to reproduce this,
Does this also create a costumer note twice? The one where you will find the transaction information link?

**Comment by Albertus58** [comment]
Also customer not twice BUT
I uninstalled the plugin, Re-installed it and now it sends all mails only once
Think you can close this one

**Comment by KoenPaas** [comment]
Indeed strange behavior thank you for the feedback!
