### ISSUE TITLE
After enabling version 1.02 I get an error displayed on all pages of my site.

### ISSUE THREAD

**Issue by xrpshine** [XRPL-Labs/xumm-for-woocommerce#12]
HI, I have updated from 0.5 to 1.02 and now have an error showing on every page of my website.

https://xrpledgernft.com

I had to change PHP from 7.4.33, which is my Hosting service recommended (Siteground) to 8.1.17 to install v1.02

Before I even enable v1.02 plugin I get the below error displayed on the front end of every page.

Warning: Undefined array key "publish" in /home/customer/www/xrpledgernft.com/public_html/wp-content/plugins/elementor/modules/usage/module.php on line 80

Elementor is a major site builder so I have to go back to PHP 7.4.33 to remove the error message, meaning I can not use v1.02!

I would imagine this will affect many xumm-for-woocommerce users and the uptake of 1.02 will not happen until Elementor Builder or a related plugin works on PHP 8.1

**Comment by WietseWind** [comment]
The error is complaining about the `modules/usage` module of Elementor. Can you check the Elementor admin panel to see if this is a module you can disable? Their docs suggest that you can turn it off:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/4756161/228219682-69b38fea-b09f-4991-828b-ea2dad50295b.png">

**Comment by spoofghost** [comment]
WordPress and a lot of plugins don't play nice with php > 8.0, Although you expect it to work at this point.

**Comment by rosseti** [comment]
@WietseWind Could we close this issue? I believe this is not connected to our plugin.
