### ISSUE TITLE
[Bug] Invalid payload when selecting XRP and no IOU selected 

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/xumm-for-woocommerce#2]
When the currency XRP is selected, and an IOU was selected but isn't anymore, a payload is composed like below. This is invalid. XRP is the native asset, so the amount should be a string with the amount in Drops, not the IOU notation.

I [fixed this at the XUMM backend for now](https://github.com/XRPL-Labs/xumm-api/commit/61bd49781c71809e5b029aaa7cfb491fd1fb0bb2) but it'd be best if it's fixed in the plugin ;)

```
"txjson": {
  "TransactionType": "Payment",
  "Destination": "ra3xiebhXA1XjmZKkA44gq9dbMbyWwEXm3",
  "Amount": {
	"currency": "XRP",
	"value": 5,
	"issuer": ""
  },
  "Memos": [
	{
		"Memo": {
			"MemoType": "68747470733A2F2F78756D6D2E6170702F",
			"MemoData": "4F726465722069643A20323832372C207061696420776974682058554D4D"
		}
	}
  ],
  "Flags": 2147483648
}
```

**Comment by KoenPaas** [comment]
Fixed in 0.5.1
